version: "3.9"
services:
  db:
    image: postgres:16
    container_name: checkpoint-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkpoint
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
